# Generated by Django 5.1.2 on 2024-10-30 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Users",
        ),
    ]
